import Head from 'next/head'
import { Button } from '../components/ui/Button'
import { Card } from '../components/Card'
import { ActivityType } from '../types/activity'
import { useState } from 'react'

export default function Home() {
  const [activity, setActivity] = useState<ActivityType>();

  async function handleActivity() {
    const response = await fetch('https://www.boredapi.com/api/activity/')
    const data = await response.json()
    setActivity(data)
  }

  return (
    <>
      <Head>
        <title>Random activities</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Card activity={activity}/>
        <Button onClick={handleActivity}/>  
      </main>
    </>
  )
}

